name: Auto finalize pull request for review

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  finalize:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mark pull request ready for review
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number,
              draft: false,
            });
